package main

import (
	_ "cheunn-panaa/golang-microservice/api/docs" // docs is generated by Swag CLI, you have to import it.
	"cheunn-panaa/golang-microservice/pkg/api"

	"log"
	"net/http"
	"sync/atomic"
	"time"

	httpSwagger "github.com/swaggo/http-swagger"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

var ready int32

func main() {
	isReady := &atomic.Value{}
	isReady.Store(false)
	go func() {
		log.Printf("Readyz probe is negative by default...")
		time.Sleep(10 * time.Second)

		atomic.StoreInt32(&ready, 1)
		log.Printf("Readyz probe is positive.")
	}()

	router := initRouter(isReady)
	http.ListenAndServe(":3000", router)
}

func initRouter(ready *atomic.Value) *chi.Mux {

	r := chi.NewRouter()
	r.Use(middleware.Logger)
	r.Get("/healthz", api.Healthz)
	r.Get("/readyz", api.Readyz)

	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:1323/swagger/doc.json"), //The url pointing to API definition
	))

	return r
}
